title: "Kate's Cool Papers"
author: "Katelyn Sadorf"
description: "Made with <b style=\"color: #f45;\">&lt;3</b> for brains and code"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
excerpt:              # extracts the first paragraph as excerpt
  separator: "\n\n\n"  # paragraph separator
  categories: []        # empty array means all categories

# Layout
show_excerpts: true
show_frame: true
show_sidebar: false
minimal: false

# Enable all default collections
defaults: []

# Menu
navigation:
  - {file: "index.html", title: "Home"}
  - {url: "/categories/", title: "Categories"}
  - {file: "README.md", title: "About"}

external:
  - {title: Email, icon: envelope, url: "mailto:ksadorf@caltech.edu"}
  - {title: GitHub, icon: github, url: "https://github.com/katelynsadorf"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/katelyn-sadorf-1b77a0194"}
  - {title: RSS, icon: rss, url: "/feed.xml"}

# Collections configuration
collections_dir: .

# Categories collection
collections:
  categories:
    output: true
    permalink: /categories/:name/
    title: Categories
    description: "Browse all categories"
    enabled: true
    sort_by: title
    sort_order: asc

# Category pages
defaults:
  - scope:
      path: ""
      type: categories
    values:
      layout: category_posts
      show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Ensure posts are included in the site
include:
  - _posts
