title: "Kate's Cool Papers"
author: "Katelyn Sadorf"
description: "Made with <b style=\"color: #f45;\">&lt;3</b> for brains and code"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: true
show_frame: true
show_sidebar: false
minimal: false

# Menu
navigation:
  - {file: "index.html", title: "Home"}
  - {file: "categories.md", title: "Categories"}
  - {file: "README.md", title: "About"}

external:
  - {title: Email, icon: envelope, url: "mailto:ksadorf@caltech.edu"}
  - {title: GitHub, icon: github, url: "https://github.com/katelynsadorf"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/katelyn-sadorf-1b77a0194"}
  - {title: RSS, icon: rss, url: "/feed.xml"}

# Optional: Enable categories/tags
collections:
  posts:
    output: true
    permalink: /:categories/:title/
  categories:
    output: true
    permalink: /categories/:name/
    title: Categories
    description: "Browse all categories"
    output: true

# Collections directory
collections_dir: .

plugins:
  - jekyll-feed
